name: Notification Cron

on:
  schedule:
    - cron: "* * * * *"   # every 1 minutes
  workflow_dispatch:        # manual trigger

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl -X POST https://fund-manager-backend-1wb8.onrender.com/api/v1/notifications/trigger